spring:
    application:
        name: spring-security
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5435/brief10?currentSchema=public
        username: postgres
        password: postgres
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update