on:
  push:
 
jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main      
      
  build:
   name: Spring build
   runs-on: ubuntu-latest
   if: ${{ needs.get-version.outputs.will-release == 'true' }}
   needs: 
      - get-version
   steps:
     - name: Print version
       run : |
         echo "${{ needs.get-version.outputs.version }}"
         echo "${{ needs.get-version.outputs.changelogs }}"
         echo "${{ needs.get-version.outputs.is-pre-release }}"
         echo "${{ needs.get-version.outputs.will-release }}"
     - name: Setup java
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: 17
     - name: Setup gradle
       uses: gradle/actions/setup-gradle@v4
     - name: Checkout clone source code
       uses: actions/checkout@v4
     - name: Build with Gradle
       env: 
         VERSION : "${{ needs.get-version.outputs.version }}"
       run: ./gradlew bootjar
      #- run: ls -lia build/libs
     - uses: actions/upload-artifact@v4
       with:
        path: build/libs
        
  test:
     name: Spring test
     runs-on: ubuntu-latest
     continue-on-error: true

     services: 
       postgres:
         image: postgres
         env:
           POSTGRES_DB: postgres
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
         options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
     steps:
       - name: Print version
         # pipe pour mettre plusieurs echo dans le run
         run: |
           echo "${{ needs.get-version.outputs.version }}"
           echo "${{ needs.get-version.outputs.changelogs }}"
           echo "${{ needs.get-version.outputs.is-prerelease }}"
           echo "${{ needs.get-version.outputs.will-release }}"
       - name: Setup java
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: 17
       - name: Setup gradle
         uses: gradle/actions/setup-gradle@v4
       - name: Checkout clone source code
         uses: actions/checkout@v4
       - name: Build with Gradle
         run: ./gradlew test
